language: node_js

node_js:
  - "6" # support only node 6.9 or higher

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8

env:
  - TRAVIS=travis CXX=g++-4.8

before_script:
  - npm install -g node-gyp

after_script: 
  - rm -rf data
  - rm -rf result